---
- name: Criando o Security Group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group gloob1
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
    rules_egress:     
  register: basic_firewall

- name: Criando a instancia EC2
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    vpc_subnet_id=subnet-06e5f728
    count={{ count }}
  user_data: |
               #!/bin/sh
               curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
               sudo apt update
               sudo apt-get install -y nodejs
               sudo apt-get install -y build-essential
               sudo apt-get install -y npm
               sudo apt-get install -y yarn
               sudo apt-get install -y unzip
               sudo apt-get install -y git
               git clone https://github.com/cirobessa/counterapp-in-ec2.git
               unzip app-counter.zip
               /usr/bin/nohup /usr/bin/node app-counter/counter.js &
  register: ec2

- name: Adicionando a instancia ao inventario temp
  add_host: name={{ item.public_ip }} groups=gloob1
  with_items: "{{ ec2.instances }}"

- name: Adicionando a instancia criada no arquivo HOSTS
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[node]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances}}"

- name: Esperando o SSH
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Adicionando um nome TAG na instancia
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: Maquina_gloob-Desafio

